### ISSUE TITLE
Patch for CiviCRM needs testing with iATS

### ISSUE THREAD

**Issue by sgladstone** [iATSPayments/com.iatspayments.civicrm#65]
Eileen has fixed an issue with CiviCRM core that should correct the issue with automated recurring contributions not having the correct bookkeeping entries.  See details at:  https://issues.civicrm.org/jira/browse/CRM-15996

Can this new API be verified to work with the iATS recurring contributions? (Both ACH and credit card)

**Comment by sgladstone** [comment]
Any news on this issue?

**Comment by adixon** [comment]
Okay, i've just checked in changes to master, which will be in the upcoming 1.4.0 release, that addresses this issue.

Specifically - all the successful contributions that are being created via the api now conform to the proper pattern of being created initially as a pending contribution and then being completed either via the completecontribution or the repeatcontribution action.

This functionality is pretty complex to test in all it's incarnations (e.g. recurring memberships), so any help you can provide testing with your specific setup would be great.

**Comment by sgladstone** [comment]
My primary concern is that the combination of Eileen's fix to core, and your changes to the iATS extension will solve the very painful issue of recurring contributions not showing up properly on the Bookkeeping Transaction Report and exported accounting batches.     

Most of my clients do NOT use automated recurring memberships. What is common: 
  - The bookkeeper initiating a recurring contribution from the "contribution" tab on a contact record
  - A donor initiating a recurring contribution from a public facing Contribution Page. (Not connected to membership)
  - for both bookkeepers and donors, multiple line items with different financial types are VERY common (ie a price set is involved)

**Comment by adixon** [comment]
Thanks - I believe the bookkeeping should be fixed now, but I do find that even when CiviCRM is working properly, the bookkeeping transactions report isn't reliable when there are line items - I need to use eileen's extended bookkeeping extension to get that. The messy piece is that both contributions and line items can have financial types.

**Comment by sgladstone** [comment]
Correct, but from an accounting point of view, only the financial types of the line items are important (and only the line item financial types/accounts need to be reflected on the data going to the general ledger.

**Comment by sgladstone** [comment]
Alan - Some additional common scenarios:

- Within a particular recurring contribution schedule, the first contribution completes normally, but later contributions fail

- Within a particular recurring contribution schedule, the first contribution fails, but later contributions are successful

**Comment by mattbaylor** [comment]
The only scenario that we are looking and needing is to have recurring donations trigger the offline receipt template based email.

**Comment by mattbaylor** [comment]
just tested the master branch and receipts are being sent for donations initiated from the admin interface. Receipt is still not being sent for donations initiated on a public page. Both recurring donations (the 1st installment, anyway) processed correctly. I'll post to let you know if we get receipts for future recurrences.

**Comment by adixon** [comment]
You won't yet, but if you're in a hurry you can look at line 273 of api/v3/Job/Iatsrecurringcontributions.php and change the 0 to a 1.

We'll make it configurable from the web interface in the future, but I didn't want to change the default and have everyone suddenly sending out receipts without knowing.

**Comment by mattbaylor** [comment]
I have installed the current "master" and set the 0 to a 1 to enable emails. Just tried a contribution (with recurrence) and haven't not received a confirmation email from the initial contribution. I'll keep you posted regarding future emails.

**Comment by mattbaylor** [comment]
So far no change in the email behavior for recurring donations. This evening I deployed the most current release (instead of the master working copy from late June) and set up a two more tests. I also re-edited line 273 of Iatsrecurringcontributions.php. Hoping for some emails from the recurring transactions!

**Comment by KarinG** [comment]
Hi Matt - what version of CiviCRM are you using? These recurring Emails were definitively going out during my 4.6 grid testing (for 1.4.0) - and since this is very different from what it always has been we thought to play it safe and Alan added in the switch he referenced above.

**Comment by mattbaylor** [comment]
We are on 4.5.8. I haven't read the release notes to see what might be impacted on an upgrade to 4.6.

**Comment by adixon** [comment]
Any chance that you've got an issue with outgoing mail? Can you manually trigger a recurring payment and look at your maillog?

Also, I do find that CiviCRM's selection of off-line vs. on-line receipt to be not always what I expect, so make sure they're both configured ...

And finallyl, I'm not entirely sure about 4.5.x, since it's not an LTS, but my guess is that it should be triggering emails.

In any case, we did confirm it was working in our tests, and it's not actually an iATS function (I'm just calling the api with the right parameters), so I'm going to close this issue unless you can give me an idea about how the iATS extension is involved.

**Comment by mattbaylor** [comment]
**Re: Closing**
makes sense to me based on your testing.

**Re: Outgoing Mail**
Thanks for the idea, however when we manually set up a recurring donation through the admin interface the outgoing mail is getting triggered and delivered, so I know outbound email from Civi is working correctly.

**Re: 4.5.x**
Since 4.5.x is not LTS I'm willing to blame that version and rely on the testing you all did for 4.6.

Thank you all for your help with this! I greatly appreciate it.
